### ISSUE TITLE
CI: Extension publishing fails

### ISSUE THREAD

**Issue by Philipp15b** [moves-rwth/caesar#21]
See https://github.com/moves-rwth/caesar/actions/runs/9150425689/job/25155182535.

I've tried to publish locally, and now I'm getting again:
> This extension consists of 1356 files, out of which 830 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore

See #16.

The CI script seems to have this `--out` parameter for which I cannot find the documentation?
```
npm run package -- --out caesar-${{ inputs.version }}.vsix
```

**Comment by darionhaase** [comment]
> I've tried to publish locally, and now I'm getting again:
> 
> > This extension consists of 1356 files, out of which 830 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
> 
> See #16.

This seems to only affect manual publishing and is not responsible for the failure of the CI. At least no such warning is present in the CI logs. I will have a look at the 'unnecessary files' problem in #16.

The workflow failed because of missing secrets, see #21. 

> The CI script seems to have this `--out` parameter for which I cannot find the documentation?
> 
> ```
> npm run package -- --out caesar-${{ inputs.version }}.vsix
> ```

This flag is used to set the filename of the extension, see https://github.com/microsoft/vscode-vsce/blob/fd9a2627e29c031829e550b9bde2ce2282d99a3d/src/main.ts#L86
